CREATE TABLE
IF NOT EXISTS contacts
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE
IF NOT EXISTS blueprints
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  filename TEXT NOT NULL,
  type TEXT NOT NULL,
  title TEXT,
  description TEXT,
  created_at TEXT NOT NULL
);