name = "dondlingergc-github-io"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "."

[env.production]
name = "dondlingergc-github-io"

[env.preview]
name = "dondlingergc-pages-staging"
