name = "dondlingergc-github-io"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "dgc"
database_id = "f473414a-c9d7-4595-996c-1afaa8691ef0"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "jdondlingermedia"

[env.production]
name = "dondlingergc-github-io"
[[env.production.d1_databases]]
binding = "DB"
database_name = "dgc"
database_id = "f473414a-c9d7-4595-996c-1afaa8691ef0"

[[env.production.r2_buckets]]
binding = "MEDIA"
bucket_name = "jdondlingermedia"

[env.preview]
name = "dondlingergc-pages-staging"
[[env.preview.d1_databases]]
binding = "DB"
database_name = "dgc"
database_id = "f473414a-c9d7-4595-996c-1afaa8691ef0"

[[env.preview.r2_buckets]]
binding = "MEDIA"
bucket_name = "jdondlingermedia"

